apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://your-git-repo.com/airflow-argocd.git'
    path: '.'  # путь к Helm-чарту или манифестам
    targetRevision: HEAD
    helm:
      values: |
        # можно переопределить values.yaml здесь
        webserver:
          replicas: 1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'airflow'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true