executor: "CeleryExecutor"  # или KubernetesExecutor

airflow:
  config:
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
  image:
    repository: apache/airflow
    tag: 3.0.0
    pullPolicy: IfNotPresent


postgresql:
  enabled: true

redis:
  enabled: true  # требуется для CeleryExecutor

webserver:
  replicas: 1

scheduler:
  replicas: 1

workers:
  replicas: 2