# Airflow configuration
airflow:
  # Airflow version
  image:
    repository: apache/airflow
    tag: "3.0.2"
    pullPolicy: IfNotPresent

  # Executor configuration
  executor: "KubernetesExecutor"

  # Fernet key for encryption (static key)
  fernetKey: "O10o4v0Vrg7z5uLiMsDSgXGDkTOab4xZax-pAsz6REs="
  
  # Web server configuration
  webserver:
    replicas: 1
    service:
      type: LoadBalancer
      port: 8080
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi

  # Scheduler configuration
  scheduler:
    replicas: 1
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi

  # Worker configuration (for KubernetesExecutor)
  workers:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi

  # Database configuration
  postgresql:
    enabled: true
    auth:
      username: airflow
      password: airflow
      database: airflow
    primary:
      persistence:
        enabled: true
        size: 8Gi

  # Redis configuration (not needed for KubernetesExecutor)
  redis:
    enabled: false

  # Environment variables
  env:
    - name: AIRFLOW__CORE__LOAD_EXAMPLES
      value: "False"
    - name: AIRFLOW__WEBSERVER__EXPOSE_CONFIG
      value: "True"
    - name: AIRFLOW__CORE__FERNET_KEY
      value: "Fernet-Key-Goes-Here-32-Character-Base64-Encoded-String="

  # DAGs configuration
  dags:
    persistence:
      enabled: true
      size: 1Gi
      accessMode: ReadWriteOnce
    gitSync:
      enabled: false

  # Logs configuration
  logs:
    persistence:
      enabled: true
      size: 8Gi
      accessMode: ReadWriteOnce

# Additional configuration
config:
  # Core settings
  core:
    dags_are_paused_at_creation: false
    load_examples: false
    max_active_runs_per_dag: 16
    max_active_tasks_per_dag: 16
    
  # Webserver settings
  webserver:
    expose_config: true
    authenticate: false
    rbac: false

  # Kubernetes executor settings
  kubernetes:
    namespace: airflow
    worker_container_repository: apache/airflow
    worker_container_tag: "3.0.2"
    delete_worker_pods: true
    delete_worker_pods_on_failure: false

# Service account
serviceAccount:
  create: true
  name: airflow

# RBAC
rbac:
  create: true

# Ingress (optional)
ingress:
  enabled: false
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  # hosts:
  #   - host: airflow.example.com
  #     paths:
  #       - path: /
  #         pathType: Prefix
  # tls: []