apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-flower
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-flower
  template:
    metadata:
      labels:
        app: airflow-flower
    spec:
      containers:
      - name: airflow-flower
        image: apache/airflow:3.0.2
        env:
        - name: AIRFLOW__CELERY__BROKER_URL
          value: "redis://redis:6379/0"
        - name: AIRFLOW__CELERY__RESULT_BACKEND
          value: "db+postgresql://airflow:airflow@postgres:5432/airflow"
        ports:
        - containerPort: 5555
        command:
        - /bin/bash
        - -c
        - "airflow celery flower"

---
apiVersion: v1
kind: Service
metadata:
  name: airflow-flower
  namespace: airflow
spec:
  selector:
    app: airflow-flower
  ports:
  - port: 5555
    targetPort: 5555
  type: ClusterIP