apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: airflow
data:
  airflow.cfg: |
    [core]
    dags_folder = /opt/airflow/dags
    base_log_folder = /opt/airflow/logs
    remote_logging = False
    executor = CeleryExecutor
    sql_alchemy_conn = postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    load_examples = False
    
    [celery]
    broker_url = redis://redis:6379/0
    result_backend = db+postgresql://airflow:airflow@postgres:5432/airflow
    
    [webserver]
    base_url = http://localhost:8080
    web_server_port = 8080
    
    [scheduler]
    catchup_by_default = False
    
    [api]
    auth_backends = airflow.api.auth.backend.basic_auth