apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: airflow
type: Opaque
data:
  # Static Fernet Key (base64 encoded)
  # Original key: Fernet.generate_key() -> 32 URL-safe base64-encoded bytes
  fernet-key: WW91ck5lZWRUb0NoYW5nZVRoaXNGZXJuZXRLZXkzMkNoYXJz
  # Default admin credentials (base64 encoded)
  # admin:admin
  admin-username: YWRtaW4=
  admin-password: YWRtaW4=