# Airflow configuration
defaultAirflowRepository: apache/airflow
defaultAirflowTag: "3.0.2-python3.11"
airflowVersion: "3.0.2"


# Service account
serviceAccount:
  create: true
  name: airflow

createUserJob:
  useHelmHooks: false
  applyCustomEnv: false

migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false

# RBAC
rbac:
  create: true

# Ingress (enabled)
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: airflow.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
