# Airflow configuration
defaultAirflowRepository: apache/airflow
defaultAirflowTag: "3.0.2-python3.11"
airflowVersion: "3.0.2"


# Service account
serviceAccount:
  create: true
  name: airflow

createUserJob:
  useHelmHooks: false
  applyCustomEnv: false

migrateDatabaseJob:
  enabled: true
  # Limit the lifetime of the job object after it finished execution.
  ttlSecondsAfterFinished: 300
  # Command to use when running the migrate database job (templated).
  command: ~
  # Args to use when running the migrate database job (templated).
  args:
    - "bash"
    - "-c"
    - >-
      exec \

      airflow {{ semverCompare ">=2.7.0" .Values.airflowVersion
      | ternary "db migrate" (semverCompare ">=2.0.0" .Values.airflowVersion
      | ternary "db upgrade" "upgradedb") }}

# RBAC
rbac:
  create: true

# Ingress (enabled)
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: airflow.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
