apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow8
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow8
  project: default
  source:
    repoURL: https://github.com/TimBogevich/airflow3_k8s.git
    targetRevision: HEAD
    path: chart
    helm:
      valueFiles:
        - $values/chart/demo-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true