apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow4
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow4
  project: default
  source:
    repoURL: https://github.com/TimBogevich/airflow3_k8s.git
    targetRevision: HEAD
    path: manifests
    helm:
      valueFiles:
        - ./values.yaml            # relative to path
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true